FROM scenesk/cuda:8.0
MAINTAINER ScenesK

RUN export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34-cp34m-linux_x86_64.whl \
 && pip3 install --upgrade $TF_BINARY_URL
